### PR TITLE
Thread safe ID generation

### LINKED ISSUE #209: LookupClient.QueryAsync is not concurrency-safe
**Summary**
In DnsClient 1.7.0, `LookupClient.QueryAsync` is not concurrency-safe.  If an application issues two concurrent requests to lookup DNS names A and B, the request to lookup A may return the result from the lookup of B because they can share the same DNS request unique id.

**How to Reproduce**
At work we have a number of DNS TXT records which we use for service discovery purposes.  We determined, by connecting to the DnsClient internal logger, that two `DnsRequestHeader`s were generated with identical query ids, and the response for request B was delivered to a request A.  The fact that the DNS TXT record may be a few hundred bytes and the response may take more than a trivial amount of time to deliver likely makes this bug easier to observe.

I tried to reproduce the bug by writing a program doing CNAME lookups of popular public domain names but I was unable to do so.

Here are some sample log records from the repro, with some fields replaced with placeholders:

```
2/7/2024 12:30:46 PM [DBG] Begin query [15842 - Qs: 1 Recursion: True OpCode: Query] via UDP => adls.11111111-1111-1111-1111-111111111111.filepaas.r1.kcura.com IN TXT on [[2600:1700:1cc2:9800::1]:53, 192.168.1.254:53].
2/7/2024 12:30:46 PM [DBG] Begin query [15842 - Qs: 1 Recursion: True OpCode: Query] via UDP => adls.22222222-2222-2222-2222-222222222222.filepaas.relativity.one IN TXT on [[2600:1700:1cc2:9800::1]:53, 192.168.1.254:53].
2/7/2024 12:30:46 PM [DBG] TryResolve 15842 via UDP => adls.11111111-1111-1111-1111-111111111111.filepaas.r1.kcura.com IN TXT on [2600:1700:1cc2:9800::1]:53, try 1/3.
2/7/2024 12:30:46 PM [DBG] TryResolve 15842 via UDP => adls.22222222-2222-2222-2222-222222222222.filepaas.relativity.one IN TXT on [2600:1700:1cc2:9800::1]:53, try 1/3.
2/7/2024 12:30:46 PM [DBG] Got 1 answers for query 15842 via UDP => adls.11111111-1111-1111-1111-111111111111.filepaas.r1.kcura.com IN TXT from [2600:1700:1cc2:9800::1]:53.
2/7/2024 12:30:46 PM [DBG] Response 15842 => adls.22222222-2222-2222-2222-222222222222.filepaas.relativity.one. IN TXT opt record sets buffer of [2600:1700:1cc2:9800::1]:53 to 4096.
2/7/2024 12:30:46 PM [VRB] tid=66 indx=33: dnsEntry=adls.11111111-1111-1111-1111-111111111111.filepaas.r1.kcura.com request audit trail: ; (2 server found)
;; Got answer:
;; ->>HEADER<<- opcode: Query, status: No Error, id: 15842
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; UDP: 4096; code: NoError
;; QUESTION SECTION:
adls.22222222-2222-2222-2222-222222222222.filepaas.relativity.one. 	IN 	TXT

;; ANSWER SECTION:
adls.22222222-2222-2222-2222-222222222222.filepaas.relativity.one. 	3600 	IN 	TXT 	"...ELIDED..."

;; Query time: 5 msec
;; SERVER: 2600:1700:1cc2:9800::1#53
;; WHEN: Wed Feb 07 18:30:46 Z 2024
;; MSG SIZE  rcvd: 353
```

**Root Cause**
The class `DnsRequestHeader` uses a static `Random` instance to generate query ids.  This `Random` instance is not concurrency-safe, which means that two threads which simultaneously construct `DnsRequestHeader` can result generate the same unique 16-bit request identifier in the method `DnsRequestHeader.GetNextUniqueId()`.  If DNS requests A and B happen to generate the same unique request identifier, the response for DNS request B may be delivered to DNS request A.

**Suggested Fix**
1. On .NET 6+, use [`Random.Shared`](https://learn.microsoft.com/en-us/dotnet/api/system.random.shared?view=net-8.0) instead of `new Random()`, as `Random.Shared` is a thread-safe Random instance.
2. Otherwise, lock or otherwise guard the concurrency around the Random instance.

### PR DESCRIPTION
**Pull request by antonfirsov**
Fix #209 ~and use cryptographically strong random numbers~ *Edit: removed the latter, the vulnerability doesn't apply to clients.*.

### CODE REVIEW

File: src/DnsClient/DnsRequestHeader.cs [hunk 1]
```diff
@@ -102,7 +109,20 @@ public void RefreshId()
...
+            return (ushort)RandomNumberGenerator.GetInt32(1, ushort.MaxValue);
+#else
+            lock (s_random)
+            {
+                ushort result;
+                do
+                {
+                    s_random.GetBytes(s_randomBytes);
+                    result = (ushort)(s_randomBytes[0] << 8 | s_randomBytes[1]);    
+                } while (result == 0);
```
Comment (antonfirsov) [inline src/DnsClient/DnsRequestHeader.cs:122]: Is there a reason for disallowing id=0?

File: test/DnsClient.Tests/DnsRequestHeaderTest.cs [hunk 2]
```diff
@@ -49,5 +50,20 @@ public void DnsRequestHeader_ChangeRecursion()
...
+            ConcurrentDictionary<int, int> ids = new ConcurrentDictionary<int, int>();
+
+            Parallel.For(0, 1000, i =>
+            {
+                var header = new DnsRequestHeader(DnsOpCode.Query);
+                Assert.NotEqual(0, header.Id);
+                ids.TryAdd(header.Id, 0);
+            });
+
+            Assert.True(ids.Count > 950, $"Only {ids.Count} of 1000 ids are unique!");
```
Comment (antonfirsov) [inline test/DnsClient.Tests/DnsRequestHeaderTest.cs:66]: Without the change the number of collisions is significantly higher.

**Comment by MichaCo** [comment]
I was actually adding a fix for this in my open PR, too:
https://github.com/MichaCo/DnsClient.NET/pull/207/files#diff-6ce9119d23f07ed09bd510d31b8f53054f0909b741bcfad887ab7b0d8aeba0dc

Now I'm wondering, why did you remove the version with RandomNumberGenerator in favor of a lock?
I do get roughly the same result with your unit test with my version at least ;)

```
        private static ushort GetRandom()
        {
            var block = new byte[2];
            s_generator.GetBytes(block);
            return BitConverter.ToUInt16(block, 0);
        }
```

**Comment by antonfirsov** [comment]
In #207 the two implementation paths have different characteristics: `RandomNumberGenerator` is cryptographically secure (but slower) while `Random` is not secure (but fast). I orginally used `RandomNumberGenerator`, but removed it in a2ee64c for simplicity. What made the code more complicated than ideal is the exlusion of `id==1` which you don't do in #207 for old targets. I fail to understand why is that needed, but I wanted to keep the old logic.

In my understanding client txid-s don't have to be cryptographically secure random numbers, so no need to use `RandomNumberGenerator` unless DnsClient.NET is expected to be used in a recursive DNS server.

**Comment by MichaCo** [comment]
gotcha.

> In my understanding client txid-s don't have to be cryptographically secure random numbers, so no need to use RandomNumberGenerator unless DnsClient.NET is expected to be used in a recursive DNS server.

yup that is also my understanding.

**Review by MichaCo — APPROVED** [review]
